import Head from 'next/head'
import Auth from "@/components/Auth"

export default function Home() {
  return (
    <div>
      <Head>
        <title>I Have a Wish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hello</h1>
        <Auth />
      </main>
      
    </div>
  )
}
