import Head from 'next/head'
import Auth from "@/components/Auth"


export default function Home({currentUser}) {
   
  return (
    <div>
      <Head>
        <title>I Have a Wish</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
     <main>
      {!currentUser && <Auth />}
      {
        currentUser && (
          <>
           <h1 className='mb-6 text-white font-semibold text-3xl '> Do you have {' '}
           <span className='text-transparent bg-clip-text bg-gradient-to-br from-purple-600 via-pink-500 to-blue-600'>something</span>{' '}
           </h1>
           to say?
          </>
        )
      }
     </main>   
         
    
      
    </div>
  )
}
